apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-db
spec:
  selector:
    matchLabels:
      app: mediawiki-db
  template:
    metadata:
      labels:
        app: mediawiki-db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: your-root-password
            - name: MYSQL_DATABASE
              value: your-database-name
            - name: MYSQL_USER
              value: your-username
            - name: MYSQL_PASSWORD
              value: your-password
          ports:
            - containerPort: 3306
              name: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-db-service
spec:
  selector:
    app: mediawiki-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

