# Base image
FROM mysql:8

# Set the MySQL root password
ENV MYSQL_ROOT_PASSWORD=root

# Create a new database for MediaWiki
ENV MYSQL_DATABASE=wikidatabase
ENV MYSQL_USER=wiki
ENV MYSQL_PASSWORD=THISpasswordSHOULDbeCHANGED

# Expose port 3306
EXPOSE 3306

